# Generated by Django 6.0.5 on 2026-06-06 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('distance', models.CharField(max_length=20)),
                ('travel_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CrewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('png', models.ImageField(upload_to='crew_images/png/')),
                ('webp', models.ImageField(upload_to='crew_images/webp/')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='space_details.crew')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('png', models.ImageField(upload_to='destination_images/png/')),
                ('webp', models.ImageField(upload_to='destination_images/webp/')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='space_details.destination')),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portrait', models.ImageField(upload_to='technology_images/portrait/')),
                ('landscape', models.ImageField(upload_to='technology_images/landscape/')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='space_details.technology')),
            ],
        ),
    ]
