# Generated by Django 6.0.5 on 2026-05-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.ManyToManyField(related_name='account', to='users.category'),
        ),
    ]
