# Generated by Django 6.0.5 on 2026-05-25 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='bio',
            field=models.TextField(default='Hello I am a user of this application', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
