# Generated by Django 6.0.5 on 2026-05-25 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_students_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.TextField()),
                ('students', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.students')),
            ],
        ),
    ]
