# Generated by Django 6.0.5 on 2026-05-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='students',
            new_name='student',
        ),
    ]
