# Generated by Django 6.0.5 on 2026-05-26 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_level_alter_posts_author_alter_profile_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=7)),
                ('course_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.course')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.level')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.students')),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='courses',
            field=models.ManyToManyField(through='users.Enrollment', to='users.course'),
        ),
        migrations.AddField(
            model_name='students',
            name='level',
            field=models.ManyToManyField(through='users.Enrollment', to='users.level'),
        ),
    ]
