# Generated by Django 6.0.5 on 2026-05-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_course_enrollment_students_courses_students_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
