# Generated by Django 6.0.5 on 2026-05-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_posts_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='courses_enrolled',
            field=models.ManyToManyField(related_name='enrolled_students', to='users.course'),
        ),
    ]
