# Generated by Django 6.0.5 on 2026-05-26 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_students_courses_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='subjects_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students_course', to='users.course'),
            preserve_default=False,
        ),
    ]
