# Generated by Django 6.0.5 on 2026-05-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_students_subjects_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='level',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='students',
            name='level',
        ),
        migrations.RemoveField(
            model_name='students',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='students',
            name='subjects_course',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
