# Generated by Django 6.0.5 on 2026-05-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_enrollment_course_remove_enrollment_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('ship_number', models.IntegerField()),
                ('location', models.CharField(max_length=250)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
    ]
