# Generated by Django 6.0.5 on 2026-05-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_captains'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('features', models.TextField()),
                ('can_fly', models.BooleanField()),
            ],
            options={
                'verbose_name': 'animals',
                'verbose_name_plural': 'animals',
            },
        ),
        migrations.AlterModelOptions(
            name='captains',
            options={'verbose_name': 'captains', 'verbose_name_plural': 'captains'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'students', 'verbose_name_plural': 'students'},
        ),
    ]
